38 feature countries
ncedu-tlt/2018-ux-simple-web pull request #56
Opened 2019-02-07 11:54 UTC by NailJusupov

Closes #38

2019-02-07 16:20 UTC, ocassio requested changes

2019-02-07 16:20 UTC, ocassio commented on src/main/java/ru/ncedu/simpleweb/servlets/countries/CountriesRemoveServlet.java
> +            if (isDeleted) {
У тебя в переменной уже boolean.

2019-02-07 16:20 UTC, ocassio commented on src/main/webapp/js/countries/delete.js
> +var tr;
А если мы сразу несколько обработчиков активируем? Тогда мы получим эффект, когда один вмешивается в работу другого.

2019-02-07 16:20 UTC, ocassio commented on src/main/webapp/js/countries/delete.js
> +        tr = this.closest('tr');
Не завязываемся на теги, они могут измениться.

2019-02-07 16:20 UTC, ocassio commented on src/main/webapp/js/countries/delete.js
> +        deleteWindow.style.display = 'flex';
Стили из JS не меняем. Манипулируем только классами.

2019-02-07 17:14 UTC, NailJusupov commented on src/main/java/ru/ncedu/simpleweb/servlets/countries/CountriesRemoveServlet.java
> +            if (isDeleted) {
Вот с этим возникла проблема. Когда я пытался напрямую записать jsonEnt.put("isSuccess", isDeleted), то приходила ошибка, как будто туда записывается не булевое значение

2019-02-08 10:11 UTC, ocassio commented on src/main/webapp/js/countries/delete.js
> +var tr;
Еще актуально.

2019-02-08 12:35 UTC, NailJusupov commented on src/main/webapp/js/countries/delete.js
> +var tr;
Так, чтобы удостовериться. Проблема в forEach? В том, что он возвращает функцию?

2019-02-08 12:55 UTC, ocassio commented on src/main/webapp/js/countries/delete.js
> +var tr;
Нет проблема в переменной tr :)

2019-02-08 16:16 UTC, ocassio approved these changes

2019-02-08 16:16 UTC, merged